/*
* Action types
*/
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ONE_BOOK_SUCCESS = 'GET_ONE_BOOK_SUCCESS';
export const GET_ONE_BOOK_FAIL = 'GET_ONE_BOOK_FAIL';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';
export const BORROW_HISTORY_SUCCESS = 'BORROW_HISTORY_SUCCESS';
export const BORROW_HISTORY_FAIL = 'BORROW_HISTORY_FAIL';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
export const BORROW_BOOK_SUCCESS = 'BORROW_BOOK_SUCCESS';
export const BORROW_BOOK_FAIL = 'BORROW_BOOK_FAIL';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const RETURN_BOOK_FAIL = 'RETURN_BOOK_FAIL';