/*
* Action types
*/
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ONE_BOOK_SUCCESS = 'GET_ONE_BOOK_SUCCESS';
export const GET_ONE_BOOK_FAIL = 'GET_ONE_BOOK_FAIL';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';
export const BORROW_HISTORY_SUCCESS = 'BORROW_HISTORY_SUCCESS';
export const BORROW_HISTORY_FAIL = 'BORROW_HISTORY_FAIL';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
export const BORROW_BOOK_SUCCESS = 'BORROW_BOOK_SUCCESS';
export const BORROW_BOOK_FAIL = 'BORROW_BOOK_FAIL';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const RETURN_BOOK_FAIL = 'RETURN_BOOK_FAIL';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const PASSWORD_FETCHING = 'PASSWORD_FETCHING';
export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';
export const REQUEST_RESET_FAIL = 'REQUEST_RESET_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const BORROW_HISTORY_FETCH= 'BORROW_HISTORY_FETCH';